### ISSUE TITLE
"LoadLibraryA() failed: (126): pdex.dll" error upon building and running in Simulator

### ISSUE THREAD

**Issue by Voxybuns** [risolvipro/playdate-mode7#1]
I wanted to run the example file to check out the library in action, so I've copied the `Source` folder into a blank project, before copying the relevant binaries (in my case, `pdex.dll` and `pdex.elf`) into the source folder, as per the instructions. However, this happens when I try to build and run the project:

```
Loading C API game: D:/Documents/Playdate Projects/Mode7Test/builds/Mode7Test.pdx/pdex.dll
LoadLibraryA() failed: (126): D:/Documents/Playdate Projects/Mode7Test/builds/Mode7Test.pdx/pdex.dll
02:46:21: Loading: OK
Update error: Could not load the Library.
02:46:21: Update failed, simulator paused.
```

**Comment by risolvipro** [comment]
Thanks for reporting it, could you try with the attached .dll file?

[pdex.dll.zip](https://github.com/risolvipro/playdate-mode7/files/13807047/pdex.dll.zip)

**Comment by Voxybuns** [comment]
That worked perfectly! ❤️ I was able to get the example running, and wow, it looks amazing!!
I was initially confused as to why the ground plane needed special treatment, but now I understand, after seeing the dynamic dithering at work. Can't wait to play around with it, thank you for creating this library!

**Comment by risolvipro** [comment]
Great!
I've updated the dll file in the repo.
